--sql startup script

CREATE TABLE IF NOT EXISTS groups (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	name CHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	firstName CHAR(128) NOT NULL,
	lastName CHAR(128) NOT NULL,
	inGroup INTEGER NULL,
	FOREIGN KEY (inGroup) REFERENCES groups(id)
);

CREATE TABLE IF NOT EXISTS teachers (
 	id INTEGER PRIMARY KEY AUTOINCREMENT,
 	firstName CHAR(128) NOT NULL,
 	lastName CHAR(128) NOT NULL,
 	mentor INTEGER NULL,
 	FOREIGN KEY (mentor) REFERENCES groups(id)
);